# Generated by Django 3.2.7 on 2021-09-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHolder',
            fields=[
                ('image', models.ImageField(upload_to='images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ip_v4', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uploaded_images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='image_analyzer.imageholder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_analyzer.user')),
            ],
        ),
    ]
