# Generated by Django 3.2.7 on 2021-09-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageholder',
            name='user_ip',
            field=models.CharField(default='', max_length=16),
        ),
    ]
