# Generated by Django 3.2.7 on 2021-09-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0002_imageholder_user_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlog',
            name='uploaded_images',
        ),
        migrations.RemoveField(
            model_name='userlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserLog',
        ),
    ]
