# Generated by Django 3.2.7 on 2021-09-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0003_auto_20210917_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageholder',
            name='image_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
