# Generated by Django 3.2.7 on 2021-09-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_analyzer', '0005_alter_imageholder_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageholder',
            name='image_path',
            field=models.CharField(default='', max_length=200),
        ),
    ]
